export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_LOADING = 'SET_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const PROFILE_LOADED = 'PROFILE_LOADED';
export const SET_LOADING_PROFILE = 'SET_LOADING_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const GET_BLOOD_DONORS = 'GET_BLOOD_DONORS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const BLOOD_DONORS_ERROR = 'BLOOD_DONORS_ERROR';

export const GET_STATES = 'GET_STATES';
export const GET_STATE_CITIES = 'GET_STATE_CITIES';
export const CLEAR_STATE_CITIES = 'CLEAR_STATE_CITIES';
export const SET_LOADING_STATES = 'SET_LOADING_STATES';
export const SET_LOADING_STATE_CITIES = 'SET_LOADING_STATE_CITIES';
export const LOCATION_ERROR = 'LOCATION_ERROR';
